apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-influxdb
spec:
    capacity:
        storage: 500Mi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: "/data/influxdb"
    volumeID: "001"                
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: pvc-influxdb
spec:
    storageClassName: manual
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 500Mi