apiVersion: apps/v1 #deployment will deploy and mange the app
kind: Deployment
metadata:
  name: nginx #name of the app
  labels:
    app: nginx
spec:
  replicas: 1 #how may pods to create
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers: #data about the container that should be runned
      - name: nginx
        image: nginx-container
        imagePullPolicy: Never #the image is assumed to exist locally. No attempt is made to pull the image.
        livenessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 5
          periodSeconds: 5 
---
#service file will be used to get user orders and map them into the pod
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:  
    metallb.universe.tf/allow-shared-ip : key
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22  
  selector:
     app: nginx   
  type: LoadBalancer
  loadBalancerIP: 192.168.99.115