apiVersion: apps/v1 #deployment will deploy and mange the app
kind: Deployment
metadata:
  name: grafana #name of the app
  labels:
    app: grafana
spec:
  replicas: 1 #how may pods to create
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers: #data about the container that should be runned
      - name: grafana
        image: grafana-container
        imagePullPolicy: Never #the image is assumed to exist locally. No attempt is made to pull the image.
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        # ports:
        # - containerPort: 3000  
---
#service file will be used to get user orders and map them into the pod
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
  annotations:  
    metallb.universe.tf/allow-shared-ip : key
spec:
  ports:
    - name: http
      port: 3000
  selector:
     app: grafana   
  type: LoadBalancer
  loadBalancerIP: 192.168.99.115
