apiVersion: apps/v1 #deployment will deploy and mange the app
kind: Deployment
metadata:
  name: ftps #name of the app
  labels:
    app: ftps
spec:
  replicas: 1 #how may pods to create
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers: #data about the container that should be runned
      - name: ftps
        image: ftps-container
        imagePullPolicy: Never #the image is assumed to exist locally. No attempt is made to pull the image.
        ports:
        livenessProbe:
          tcpSocket:
            port: 21
          initialDelaySeconds: 5
          periodSeconds: 5 
---
#service file will be used to get user orders and map them into the pod
apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:  
    metallb.universe.tf/allow-shared-ip : key
spec:
  ports:
      - name: f
        port: 21
      - name: t
        port: 30000
      - name: p
        port: 30001  
      - name: s
        port: 30002
      - name: q
        port: 30003
      - name: w
        port: 30004 
  selector:
     app: ftps   
  type: LoadBalancer
  loadBalancerIP: 192.168.99.115        
