# apiVersion: v1
# kind: Pod #maybe useless #service a la place
# metadata:
#     name: mypod
# spec:
#     containers: #volume is mounted into the container
#         - name: mysql
#           image: mysql
#           volumeMounts: 
#           - mountPath: "/var/lib/mysql"
#             names: mypod
#             volumes:
#                 - name: mypod
#     volumes: #volume is mounted into the pod #mettre ca dans service ou deployment
#         - name: mypod
#           persistentVolumeClaim:
#             claimName: pvc-mysql             
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-mysql
spec:
    capacity:
        storage: 500Mi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: "/data/mysql"
    volumeID: "001"                
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: pvc-mysql
spec:
    storageClassName: manual
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 500Mi